version: '3.5'
services:
  elastic:
    labels:
      - "traefik.frontend.rule=PathPrefix:/elastic"
      - "traefik.frontend.rule=PathPrefixStrip:/elastic"
      - "traefik.frontend.auth.basic=enk:$$apr1$$.fGwMdNh$$MqtT50Ihijl8GmoaGaaT31"
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    environment:
    - discovery.type=single-node
    - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
    - xpack.graph.enabled=true
    - xpack.security.enabled=false
    ports:
    - 9300:9300
    - 9200:9200
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://elastic:9200
      interval: 5s
      timeout: 120s
      retries: 5

  nifi:
    labels:
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.frontend.passHostHeader=false"
      - "traefik.frontend.headers.customRequestHeaders=X-ProxyPort:${PROXY_PORT}||X-ProxyScheme:http||X-ProxyContextPath:/||X-ProxyHost:${PROXY_HOST}"
      - "traefik.frontend.auth.basic=enk:$$apr1$$.fGwMdNh$$MqtT50Ihijl8GmoaGaaT31"
    build: ./nifi/
    environment:
      - NIFI_WEB_PROXY_CONTEXT_PATH=""
      - NIFI_WEB_PROXY_HOST=${PROXY_HOST}
    ports:
    - 8080:8080
    - 8181:8181
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://nifi:8080
      interval: 5s
      timeout: 60s
      retries: 5

  kibana:
    labels:
      - "traefik.frontend.rule=PathPrefix:/kibana"
      - "traefik.frontend.rule=PathPrefixStrip:/kibana"
      - "traefik.frontend.auth.basic=enk:$$apr1$$.fGwMdNh$$MqtT50Ihijl8GmoaGaaT31"
    image: docker.elastic.co/kibana/kibana:6.4.2
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://elastic:9200
      SERVER_BASEPATH: /kibana
    ports:
    - 5601:5601
    depends_on:
    - elastic
    healthcheck:
      test:
      - CMD
      - curl
      - -f
      - http://kibana:5601
      interval: 5s
      timeout: 60s
      retries: 5

  reverse-proxy:
#    labels:
#      - "traefik.frontend.auth.basic.usersFile=/path/.htpasswd"
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "88:80"     # The HTTP port
      - "8088:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
